name: appli

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./database.db:/data/database.db
  front:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - API_URI="http://api:5001"