name: appli

services:
  front:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - API_URI="http://api:5002"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    volumes:
      - ./database.db:/data/database.db