FROM python:3.9-alpine

RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
        gcc \
        musl-dev \
        libffi-dev \
        openssl-dev \
        python3-dev \
        bash && \
    pip install flask requests
    
WORKDIR /front-end
COPY . /front-end
EXPOSE 5002
CMD ["python3", "front-end.py"]