FROM python:3.14.0a2-alpine3.20

RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
        gcc \
        musl-dev \
        libffi-dev \
        openssl-dev \
        python3-dev \
        bash

WORKDIR /front-end
COPY . /front-end
EXPOSE 5001
CMD ["python3", "front-end.py"]